name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        docker --version
        docker build -t pneumonia-app .
      env:
        DOCKER_CLI_ACI_URL: https://github.com/actions/docker/releases/download/1.3.0/docker-linux-arm64
        DOCKER_CLI_ARCH: arm64

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and tag Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .
        docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:${{ github.sha }}
      env:
        DOCKER_BUILDKIT: 1

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}